site_name: 我的知识库  # 设置网站标题
site_url: https://your_gitee_name.gitee.io/your_repo_name/ # 后续替换为你的 Gitee Pages URL

# 设置导航栏
nav:
    - 首页: index.md
    #- 关于: about.md  # 如需，可在 docs 下创建 about.md 文件

# 选择主题（可选）
theme:
    name: readthedocs    # 取消注释并使用 material 主题
    # 取消下面任意功能的注释以启用
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.path
        - navigation.top